# key is a case insensitive header key
# value is a trimmed case-insensitive regex
# target is either special folder or exact name (normalized unicode string, not UTF7)
# special folders: ""INBOX", "\\Sent", "\\Trash", "\\Junk", "\\Drafts", "\\Archive"

[[spamHeader]]
# If this header exists and starts with "yes" then the message is treated as spam
# This is SpamAssassin header.
key="X-Spam-Status"
value="^yes"
target="\\Junk"

[[spamHeader]]
# If this header exists and starts with "yes" then the message is treated as spam
# This is Rspamd header. For the same with SpamAssassin use "X-Spam-Status"
key="X-Rspamd-Spam"
value="^yes"
target="\\Junk"

# Treat as spam if message has header with 6 or more plus signs:
#   X-Rspamd-Bar: ++++++
[[spamHeader]]
key="X-Rspamd-Bar"
value="^\\+{6}"
target="\\Junk"

[[spamHeader]]
# If this header has a value, then it contains a virus, treat as spam
key="X-Haraka-Virus"
value="."
target="\\Junk"
